import os
import json
import sqlite3
import random
import requests
import google.generativeai as genai
from datetime import date, timedelta
from newsapi import NewsApiClient
import admin_manager  # <--- Crucial Import

# Define database path
DB_PATH = os.path.join(os.getenv('RENDER_DISK_PATH', '.'), 'content.db')

# --- 1. PERPLEXITY GENERATOR (Automated) ---
def generate_with_perplexity(headline):
    """Attempts to generate content using Perplexity for the automated job."""
    print("   >> Attempting generation with Perplexity...")
    pplx_api_key = os.getenv("PPLX_API_KEY")
    if not pplx_api_key: raise Exception("PPLX_API_KEY not set.")

    # --- FETCH DYNAMIC PROMPTS ---
    prompts = admin_manager.get_prompts()
    system_prompt = f"{prompts['article_creative']}\n\n{prompts['article_technical']}"
    
    user_prompt = f"Generate the structured JSON for this headline: {headline}"
    
    api_url = "https://api.perplexity.ai/chat/completions"
    headers = {"accept": "application/json", "content-type": "application/json", "authorization": f"Bearer {pplx_api_key}"}
    payload = {"model": "sonar", "messages": [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_prompt}]}
    
    response = requests.post(api_url, headers=headers, data=json.dumps(payload))
    response.raise_for_status()
    
    ai_response_text = response.json()['choices'][0]['message']['content']
    json_start = ai_response_text.find('{')
    json_end = ai_response_text.rfind('}') + 1
    return json.loads(ai_response_text[json_start:json_end])

# --- 2. GEMINI GENERATOR (Automated Fallback) ---
def generate_with_gemini(headline, description):
    """Attempts to generate content using Gemini as a fallback."""
    print("   >> Attempting generation with Gemini (Fallback)...")
    gemini_api_key = os.getenv("GEMINI_API_KEY")
    if not gemini_api_key: raise Exception("GEMINI_API_KEY not set.")
    
    genai.configure(api_key=gemini_api_key)
    model = genai.GenerativeModel('models/gemini-2.5-flash')

    # --- FETCH DYNAMIC PROMPTS ---
    prompts = admin_manager.get_prompts()
    system_instruction = f"{prompts['article_creative']}\n\n{prompts['article_technical']}"
    
    full_prompt = f"{system_instruction}\n\nHEADLINE: {headline}\nCONTEXT: {description}"
    
    response = model.generate_content(full_prompt)
    json_str = response.text.strip()
    if json_str.startswith('```json'): json_str = json_str[7:]
    if json_str.endswith('```'): json_str = json_str[:-3]
    return json.loads(json_str)

# --- 3. MAIN AUTOMATED JOB ---
def fetch_and_save_content():
    print("--- Running the v3.1 AI Content Journalist (Dynamic Prompts) ---")
    
    # 1. Fetch Headline
    try:
        print("Fetching a recent headline from NewsAPI...")
        news_api_key = os.getenv("NEWS_API_KEY")
        if not news_api_key: raise Exception("NEWS_API_KEY not set.")
        newsapi = NewsApiClient(api_key=news_api_key)
        keywords = 'tech OR gadget OR smartphone OR AI OR startup'
        sources = 'the-times-of-india,the-hindu,google-news-in,techcrunch'
        yesterday = (date.today() - timedelta(days=1)).isoformat()
        all_articles = newsapi.get_everything(q=keywords, sources=sources, language='en', from_param=yesterday, sort_by='relevancy', page_size=50)
        articles = all_articles.get("articles")
        if not articles: raise Exception("No recent articles found.")
        
        random_article = random.choice(articles)
        headline = random_article.get('title')
        description = random_article.get('description') or headline
        url = random_article.get('url')
        image_url = random_article.get('urlToImage')
        
        if not all([headline, url, image_url]): raise Exception("Article missing data.")
        print(f"Found article: {headline}")
    except Exception as e:
        print(f"Error fetching from NewsAPI: {e}"); return

    # 2. Generate Content
    ai_data = None
    try:
        ai_data = generate_with_perplexity(headline)
        print(">> Success! Content generated by Perplexity.")
    except Exception as e:
        print(f"!! Perplexity failed: {e}")
        print("!! Switching to Gemini fallback...")
        try:
            ai_data = generate_with_gemini(headline, description)
            print(">> Success! Content generated by Gemini.")
        except Exception as e_gem:
            print(f"!! FATAL: Both AIs failed. Gemini error: {e_gem}")
            return

    # 3. Save to Database
    try:
        # Use new AI title if available
        final_headline = ai_data.get('title', headline)
        
        print("Saving to database...")
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS articles (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                headline TEXT NOT NULL, commentary TEXT NOT NULL, article_url TEXT,
                image_url TEXT, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                slug TEXT UNIQUE, meta_description TEXT, image_alt_text TEXT
            )
        ''')
        
        cursor.execute('SELECT id FROM articles WHERE slug = ?', (ai_data['slug'],))
        if cursor.fetchone(): ai_data['slug'] = f"{ai_data['slug']}-{random.randint(100, 999)}"

        cursor.execute(
            'INSERT INTO articles (headline, commentary, article_url, image_url, slug, meta_description, image_alt_text) VALUES (?, ?, ?, ?, ?, ?, ?)',
            (final_headline, ai_data['commentary'], url, image_url, ai_data['slug'], ai_data['meta_description'], ai_data['image_alt_text'])
        )
        conn.commit(); conn.close()
        print("Content saved successfully!")
    except Exception as e:
        print(f"Error saving to database: {e}")

# --- 4. INSTANT ARTICLE (Manual Admin Tool) ---
def create_instant_article(topic, provider="perplexity", custom_image_url=None):
    """Generates an article based on a specific Admin topic."""
    print(f"--- Running Instant Article for: {topic} using {provider.upper()} ---")
    ai_data = None
    
    # --- FETCH DYNAMIC PROMPTS ---
    prompts = admin_manager.get_prompts()
    system_instruction = f"{prompts['article_creative']}\n\n{prompts['article_technical']}"
    user_instruction = f"Write a blog post about this topic: {topic}"

    try:
        if provider == "perplexity":
            pplx_api_key = os.getenv("PPLX_API_KEY")
            if not pplx_api_key: raise Exception("PPLX_API_KEY not set.")
            api_url = "https://api.perplexity.ai/chat/completions"
            headers = {"accept": "application/json", "content-type": "application/json", "authorization": f"Bearer {pplx_api_key}"}
            payload = {"model": "sonar", "messages": [{"role": "system", "content": system_instruction}, {"role": "user", "content": user_instruction}]}
            response = requests.post(api_url, headers=headers, data=json.dumps(payload))
            response.raise_for_status()
            ai_response_text = response.json()['choices'][0]['message']['content']
            json_start = ai_response_text.find('{')
            json_end = ai_response_text.rfind('}') + 1
            ai_data = json.loads(ai_response_text[json_start:json_end])

        elif provider == "gemini":
            gemini_api_key = os.getenv("GEMINI_API_KEY")
            if not gemini_api_key: raise Exception("GEMINI_API_KEY not set.")
            genai.configure(api_key=gemini_api_key)
            model = genai.GenerativeModel('models/gemini-2.5-flash')
            full_prompt = f"{system_instruction}\n\n{user_instruction}"
            response = model.generate_content(full_prompt)
            json_str = response.text.strip()
            if json_str.startswith('```json'): json_str = json_str[7:]
            if json_str.endswith('```'): json_str = json_str[:-3]
            ai_data = json.loads(json_str)

        if not ai_data: raise Exception("No data returned from AI.")

        # --- IMAGE SELECTION ---
        final_image_url = custom_image_url if custom_image_url else "https://images.unsplash.com/photo-1504711434969-e33886168f5c?q=80&w=2070&auto=format&fit=crop"
        
        # --- SAVE ---
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute('''CREATE TABLE IF NOT EXISTS articles (id INTEGER PRIMARY KEY AUTOINCREMENT, headline TEXT, commentary TEXT, article_url TEXT, image_url TEXT, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP, slug TEXT UNIQUE, meta_description TEXT, image_alt_text TEXT)''')
        cursor.execute('SELECT id FROM articles WHERE slug = ?', (ai_data['slug'],))
        if cursor.fetchone(): ai_data['slug'] = f"{ai_data['slug']}-{random.randint(100, 999)}"

        cursor.execute(
            'INSERT INTO articles (headline, commentary, article_url, image_url, slug, meta_description, image_alt_text) VALUES (?, ?, ?, ?, ?, ?, ?)',
            (ai_data['title'], ai_data['commentary'], "https://google.com", final_image_url, ai_data['slug'], ai_data['meta_description'], ai_data['image_alt_text'])
        )
        conn.commit(); conn.close()
        print(f"Instant article '{ai_data['title']}' created successfully using {provider}!")
        return True

    except Exception as e:
        print(f"Error creating instant article: {e}")
        return False
# --- SANDBOX TEST FUNCTION ---
def test_prompt_generation(topic, creative_prompt, technical_prompt, provider="gemini"):
    """
    Runs a dry-run generation using the provided prompts (not the saved ones).
    Returns the raw text response.
    """
    print(f"--- Running Test Bench for: {topic} ---")
    
    # Construct the system instruction from the input args
    system_instruction = f"{creative_prompt}\n\n{technical_prompt}"
    
    try:
        if provider == "gemini":
            gemini_api_key = os.getenv("GEMINI_API_KEY")
            if not gemini_api_key: return "Error: GEMINI_API_KEY not set."
            
            genai.configure(api_key=gemini_api_key)
            model = genai.GenerativeModel('models/gemini-2.5-flash')
            
            # Combine instruction + topic
            full_prompt = f"{system_instruction}\n\nTopic/Product: {topic}"
            
            response = model.generate_content(full_prompt)
            return response.text

        elif provider == "perplexity":
            pplx_api_key = os.getenv("PPLX_API_KEY")
            if not pplx_api_key: return "Error: PPLX_API_KEY not set."
            
            api_url = "https://api.perplexity.ai/chat/completions"
            headers = {"accept": "application/json", "content-type": "application/json", "authorization": f"Bearer {pplx_api_key}"}
            payload = {
                "model": "sonar", 
                "messages": [
                    {"role": "system", "content": system_instruction}, 
                    {"role": "user", "content": f"Topic/Product: {topic}"}
                ]
            }
            
            response = requests.post(api_url, headers=headers, data=json.dumps(payload))
            if response.status_code != 200:
                return f"Error: Perplexity API returned {response.status_code} - {response.text}"
                
            return response.json()['choices'][0]['message']['content']
            
    except Exception as e:
        return f"Exception during generation: {e}"
if __name__ == "__main__":
    fetch_and_save_content()